name: Deploy to mittwald Container Hosting

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with zerodeploy
        uses: mittwald/zerodeploy-action@v1
        with:
          mittwald-api-token: ${{ e87e9e5b-546f-4b7d-b9ab-27e9d37004a5:qRt6nAzcl4ZtePtUIJn7a2HEQegcTN3K0XaQgK49Dnc:mittwald_a }}
          mittwald-project-id: "p-zhda4j"
